#!/usr/bin/env bash
# configure the domain zone so www points to the load balancer lb-01

subdomains=("www" "lb-101" "web-01" "web-02")
domain="$1"
sub="$2"
dig()
{
    sub="$2"
    INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2' )"
    IP=$(echo "$INFO" | awk '{print $5}')
    RECORD=$(echo "$INFO" | awk '{print $4}')

    echo "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ $# -eq 1 ]; then
    for sub in "${subdomains[@]}"; do
        dig "$domain" "$sub"
    done
elif [ $# -eq 2 ]; then
    dig "$domain" "$sub"
fi
