#!/usr/bin/env bash
# configure ngix server so that /redirect_me 
# will redirect to www.google.com

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me http://www.google.com permanent;' /etc/nginx/sites-available/default
sudo service restart nginx
