#!/usr/bin/env bash
# configure nginx server so that /redirect_me 
# will redirect to www.google.com

sudo apt-get -y update
sudo apt-get -y install nginx
#sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
rep_string="server_name _;\n\trewrite \^/redirect_me http:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$rep_string" /etc/nginx/sites-available/default
sudo service restart nginx
