#!/usr/bin/env bash
# configure nginx server so that /redirect_me 
# will redirect to www.google.com

sudo apt-get -y update
sudo apt-get -y install nginx
#sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
rep_string="server_name _;\n\trewrite \^/redirect_me http:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$rep_string" /etc/nginx/sites-available/default
sudo service restart nginx
# custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_rep="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_rep/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
