#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get update
sudo apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    add_header X-Served-By $HOSTNAME;

    location /redirect_me {
        return 301 http://www.google.com;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default
