#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get update
sudo apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

server_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    add_header X-Served-By $HOSTNAME;

    rewrite ^/redirect_me https://github.com/aelabassi permanent;
    error_pag 404 /404.html;
    location = /404.html {
        internal;
    }
}" 
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi

