#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
balancer="\
frontend haproxy
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 455510-web-01 54.237.5.6:80 check 
    server 455510-web-02 100.26.221.163:80 check
"

# update package list

apt-get -y update
apt-get -y upgrade
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.5
apt-get -y update
# install haproxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
