#!/usr/bin/env bash
# whoami
function Whoami(){
    if [ -z "$1" ]; then
        echo -e "I never met this guy in my life"
    else
        sudo su "$1" -s /bin/bash --command=whoami
    fi
}
Whoami "$1"
